accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('signup/', views.signup_view, name="signup"),
    path('profile/', views.profile_view, name="profile"),
]

amigurimistore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar

urlpatterns = [
    path('', include('products.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('__debug__', include(debug_toolbar.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('<int:product_id>/detail', views.get_detail, name="detail"),
    path('<int:product_id>/add-comment', views.add_new_comment, name="add_new_comment"),
    path('category/<int:category_id>', views.get_products_by_category, name="category"),
]

accounts/models.py
from django.db import models

# Create your models here.

products/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.utils import timezone

from django.contrib.auth.models import User


# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=255)
    sku = models.CharField(max_length=15, validators=[MinLengthValidator(10)])
    description = models.TextField()

    category = models.ForeignKey(
        "Category", on_delete=models.CASCADE, related_name="products", null=True)
    image = models.ImageField(
        null=True, blank=True, upload_to='media/fotos')

    price = models.DecimalField(max_digits=10, decimal_places=2)

    creation_date = models.DateTimeField(default=timezone.now)
    # published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return f'{self.sku} | {self.name} - ${self.price}'


class Category(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()

    discount = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Categories"


class Comments(models.Model):
    text = models.TextField()
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, null=True,
        related_name="comments"
    )
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True
    )
    creation_date = models.TimeField(default=timezone.now)

    def __str__(self):
        return self.text[:14] if len(self.text) > 15 else self.text

products/forms.py
from django import forms

from products.models import Comments


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comments

        fields = ("text", )

        widgets = {
            "text": forms.Textarea(attrs={
                'class': 'form-control',
                'rows': '3',
                'placeholder': 'Escribe tu comentario'
            })
        }

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import login, logout


# Create your views here.
def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('index')
    else:
        form = AuthenticationForm()
    return render(request, "users/login.html", {'form': form})


def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect("login")


def signup_view(request):
    if request.method == "POST":
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('index')
    else:
        form = UserCreationForm()
    return render(request, "users/signup.html", {'form': form})


def profile_view(request):
    return render(request, 'users/profile.html', {})

products/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required, permission_required
from products.models import Product, Category
from .forms import CommentForm


# Create your views here.
# @login_required
def get_detail(request, product_id):
    product = Product.objects.prefetch_related("comments__user").get(id=product_id)

    comments = product.comments.order_by('creation_date').all()

    form = CommentForm()

    context = {
        'title': product.name,
        "product": product,
        "form": form,
        'comments': comments,
    }
    return render(request, 'products/detail.html', context)


def index(request):
    products = Product.objects.select_related("category").all()
    context = {'products': products}
    return render(request, "products/index.html", context)


@login_required
def get_products_by_category(request, category_id):
    category = Category.objects.prefetch_related("products").get(id=category_id)
    # products = Product.objects.select_related("category").filter(category=category)
    products = category.products.all()

    context = {
        'title': category.name,
        'category': category,
        'products': products,
    }
    return render(request, 'products/index.html', context)


@login_required
def add_new_comment(request, product_id):
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            user = request.user
            new_comment = form.save(commit=False)
            new_comment.user = user
            new_comment.product = Product.objects.get(id=product_id)
            new_comment.save()
        return redirect('detail', product_id=product_id)
    else:
        return redirect('detail', product_id=product_id)

templates/common/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}{% endblock title %}</title>
        <meta name="description" content="Mi primera tienda de barrio virtual">
        <meta name="keywords" content="ecomerce, market">
        {# Boostrap  #}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" />
        {# Style  #}
        <link rel="stylesheet" href="{% static 'style.css' %}">
    </head>
    <body>
        {# Navbar #}
        {% include 'common/navbar.html' %}
        {% block content %}
        {% endblock content %}
    </body>
</html>

templates/common/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'index' %}">Amigurumi Store</a>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'category' 1 %}">Animales</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'category' 2 %}">Animales Fantasticos</a>
            </li>
            
            {% if user.is_authenticated %}
                <li class="nav-item">
                <a class="nav-link" href="{% url 'profile' %}">{{ user.username }}</a>
                </li>
                <li class="nav-item">
                <form action="{% url 'logout' %}" method="post" class="d-inline">
                    {% csrf_token %}
                    <button type="submit" class="nav-link">Logout</button>
                </form>
                </li>
            {% else %}
                <li class="nav-item">
                <a class="nav-link" href="{% url 'signup' %}">Registrarse</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
            {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/products/detail.html
{% extends 'common/base.html' %}

{% block title %}
    {% if title %}
        {{ title }}
    {% else %}
        amigurimi store
    {% endif %}
{% endblock title %}

{% block content %}
    <div class="container my-5">

        <!-- Productos -->
        <div class="card mb-5 shadow">
            <div class="row g-0">
                <div class="col-md-5">
                    <img src="{{ product.image.url }}" alt="imagen del roducto" class="product-image" />
                </div>
                <div class="col-md-7">
                    <div class="card-body">
                        <h2 class="card-title">{{ product.name.username }}</h2>
                        <p class="text-muted">SKU:{{ product.sku }}</p>
                        <p class="card-text">{{ product.description }}</p>
                        <h4 class="text-primary">Precio: ${{ product.price }}</h4>
                        <button class="btn btn-success">Añadir al carrito</button>
                    </div>
                </div>
            </div>
        </div>

        <!-- comentarios  -->
        <div class="mb-4">
            <h4>Comentarios</h4>
            
            {% if perms.product.add_comments %}
            <form class="mb-3" action="{% url 'add_new_comment' product.id %}" method="POST">
                {% csrf_token %}
                <div class="mb-2">{{ form.text }}</div>
                <button type="submit" class="btn btn-primary">Publicar comentario</button>
            </form>
            {% endif %}
            
            <!-- lista comentarios  -->
            
            {% for comment in comments %}
            <div class="comment">
                <p>
                    <strong>{{ comment.user.username }}</strong><small class="text-muted">- {{ comment.creation_date }}</small>
                    <p>{{ comment.text }}</p>
                </p>
            </div>
            {% endfor %}
        </div>

    </div>
{% endblock content %}

templates/products/index.html
{% extends 'common/base.html' %}

{% block title %}
    {% if title %}
        {{ title }}
    {% else %}
        amigurimi store
    {% endif %}
{% endblock title %}

{% block content %}
<div class="container my-5">

    {% if category %}
    <h1 class="text-center mb-4">Catálogo de Productos - {{ category.name }}</h1>
    {% else %}
    <h1 class="text-center mb-4">Catálogo de Productos</h1>
    {% endif %}
    
    <div class="container">
        <div class="row row-cols-1 row-cols-md-3 g4">
            {% for product in products %}
                <div class="col">
                    <div class="card h-100">
                        <img src="{{ product.image.url }}" class="card-img-top" alt="Producto 1">
                        <div class="card-body">
                            <h5 class="card-title">{{ product.name }}</h5>
                            <p class="card-text">{{ product.description }}</p>
                            <p class="fw-bold">Precio: ${{ product.price }}</p>
                            <p class="text-muted">SKU: {{ product.sku }}</p>
                        </div>
                        <div class="card-footer text-center">
                            <a class="btn btn-primary" href="{% url 'detail' product_id=product.id %}">Ver Detalle</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>¿
</div>
{% endblock content %}

templates/users/login.html
{% extends 'common/base.html' %}

{% block content %}
<div class="login d-flex align-items-center justify-content-center">
    <div class="login__card w-100" style="max-width: 400px;">
        <h3 class="text-center mb-4">Iniciar Sesión</h3>
        <form action="{% url 'login' %}" method='post'>
            {% csrf_token %}
            {{ form }}
            <div class="d-grid">
                <button type="submit" class="btn btn-primary">Entrar</button>
                <a href="{% url 'signup' %}" class="login__link">No tienes un usuario? Registrate aqui</a>
            </div>
        </form>
    </div>
</div>
    
{% endblock content %}
    

templates/users/profile.html
{% extends 'common/base.html' %}

{% block content %}
    <div class="profile my-5">
        <div class="profile__card text-center">
            <h2 class="mb-3">Hola, <span id="user-name">{{user.username}}</span></h2>
            <form action="{% url 'logout' %}" method="post" class="d-inline">
                {% csrf_token %}
                <button class="btn btn-danger">Cerrar Sesión</button>
            </form>
        </div>
    </div>
{% endblock %}

templates/users/signup.html
{% extends 'common/base.html' %}
{% block content %}
    <div class="login d-flex align-items-center justify-content-center">
    <div class="login__card w-100" style="max-width: 400px;">
        <h3 class="text-center mb-4">Iniciar Sesión</h3>
        <form action="{% url 'signup' %}" method="post">
        {% csrf_token %}
        <div class="mb-3">
            {{ form }}
        </div>
        <div class="d-grid">
            <button type="submit" class="btn btn-primary">Entrar</button>
        </div>
        <a href="{% url 'login' %}" class="login__link">¿Ya tienes usuario? Inicia sesión aquí</a>
        </form>
    </div>
    </div>

    {% if messages %}
    <ul>
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
{% endblock %}